services:
  - type: web
    name: bethelmind-platform
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /api/health-check?quick=true
